/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PrivateDashboardRouteRouteImport } from './routes/_private/dashboard/route'
import { Route as PrivateProfileIndexRouteImport } from './routes/_private/profile/index'
import { Route as PrivateDashboardIndexRouteImport } from './routes/_private/dashboard/index'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDashboardRouteRoute = PrivateDashboardRouteRouteImport.update({
  id: '/_private/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/_private/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDashboardIndexRoute = PrivateDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/dashboard/': typeof PrivateDashboardIndexRoute
  '/profile/': typeof PrivateProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/' | '/dashboard/' | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/profile'
  id:
    | '__root__'
    | '/_private/dashboard'
    | '/_public/'
    | '/_private/dashboard/'
    | '/_private/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateDashboardRouteRoute: typeof PrivateDashboardRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof PrivateDashboardIndexRouteImport
      parentRoute: typeof PrivateDashboardRouteRoute
    }
  }
}

interface PrivateDashboardRouteRouteChildren {
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
}

const PrivateDashboardRouteRouteChildren: PrivateDashboardRouteRouteChildren = {
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
}

const PrivateDashboardRouteRouteWithChildren =
  PrivateDashboardRouteRoute._addFileChildren(
    PrivateDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PrivateDashboardRouteRoute: PrivateDashboardRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
